# Generated by Django 3.2.25 on 2024-04-29 06:06

import DoctorAssistanceApp.models
from django.db import migrations, models

def insert_user_data(apps, schema_editor):
    User = apps.get_model('DoctorAssistanceApp', 'User')
    # Add your data insertion logic here
    User.objects.create(
        user_type='admin',
        name='Admin',
        contact='1234567890',
        email='admin@example.com',
        password='admin',
        address='admin address',
        dob='2000-01-01'  # Or any default date you prefer
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(blank=True, default='null', max_length=10)),
                ('dob', models.DateField()),
                ('weight', models.CharField(blank=True, default='null', max_length=10)),
                ('address', models.TextField(blank=True, default=None)),
                ('password', models.CharField(blank=True, default=None, max_length=200)),
                ('image', models.ImageField(blank=True, default='user.png', upload_to=DoctorAssistanceApp.models.user_image_filename)),
                ('is_active', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.RunPython(insert_user_data),

    ]
