# Generated by Django 3.2.25 on 2024-04-29 06:42

import DoctorAssistanceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAssistanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(blank=True, default='null', max_length=10)),
                ('specialization', models.CharField(blank=True, default='null', max_length=100)),
                ('address', models.TextField(blank=True, default=None)),
                ('image', models.ImageField(blank=True, default='user.png', upload_to=DoctorAssistanceApp.models.user_image_filename)),
                ('is_active', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
